tap "gigalixir/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
brew "erlang"
brew "elixir"
brew "git"
brew "mas"
brew "postgresql", restart_service: true
brew "redis", restart_service: true
brew "watchman"
brew "yarn"
brew "zsh"
brew "gigalixir/brew/gigalixir"
cask "alfred"
cask "bartender"
cask "brave-browser"
cask "cryptomator"
cask "font-hack-nerd-font"
cask "font-victor-mono-nerd-font"
cask "google-chrome"
cask "gpg-suite"
cask "iterm2"
cask "postico"
cask "spotify"
cask "visual-studio-code"
mas "AdGuard for Safari", id: 1440147259
mas "CleanMyMac X", id: 1339170533
mas "Day One", id: 1055511498
mas "Flow", id: 1423210932
mas "iStat Menus", id: 1319778037
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Paste", id: 967805235
mas "Telegram", id: 747648890
