tap "homebrew/bundle"
tap "planetscale/tap"
brew "autoconf"
brew "asdf"
brew "bat"
brew "bat-extras"
brew "flyctl"
brew "fop"
brew "fzf"
brew "git"
brew "git-delta"
brew "git-town"
brew "openssl@1.1"
brew "libxslt"
brew "mas"
brew "mysql-client"
brew "ripgrep"
brew "tldr"
brew "wxwidgets"
brew "zoxide"
brew "planetscale/tap/pscale"
cask "alfred"
cask "balenaetcher"
cask "bartender"
cask "beekeeper-studio"
cask "brave-browser"
cask "calibre"
cask "cryptomator"
cask "discord"
cask "firefox"
cask "gpg-suite"
cask "insomnia"
cask "iterm2"
cask "numi"
cask "obsidian"
cask "raspberry-pi-imager"
cask "rewind"
cask "signal"
cask "torguard"
cask "visual-studio-code"
mas "AdGuard for Safari", id: 1440147259
mas "Bitwarden", id: 1352778147
mas "CleanMyMac X", id: 1339170533
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Paste", id: 967805235
mas "Telegram", id: 747648890
mas "World Clock", id: 956377119
